name: Build macOS
on:
  workflow_dispatch: {}
jobs:
  Build_macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - name: Create rhttp directory structure to resolve dependency
        run: mkdir -p ../rhttp/rhttp/lib
      - run: echo 'name: rhttp\ndescription: A new Dart package\nversion: 0.0.1\nenvironment:\n  sdk: ">=3.0.0 <4.0.0"\ndependencies:\n  flutter:\n    sdk: flutter\n' > ../rhttp/rhttp/pubspec.yaml
      - run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter build macos --release
      - uses: actions/upload-artifact@v4
        with:
          name: pixez-macos
          path: build/macos/Build/Products/Release/pixez.app
